name: open-games-hs
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges & other contributors
maintainer: juleshedges.invariant@gmail.com
copyright: 2020 Jules Hedges & other contributors
license: AGPL
github: jules-hedges/open-games-hs
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
    - Engine.BayesianGames
    - Engine.Diagnostics
    - Engine.OpenGames
    - Engine.OpticClass
    - Engine.TLL
    - Preprocessor.AbstractSyntax
    - Preprocessor.Compile
    - Preprocessor.Lambda
    - Preprocessor.Parser
    - Preprocessor.THSyntax
    - Preprocessor.TH
    - Preprocessor.Types
    - Examples.Bimatrix
    - Examples.Bayesian
    - Examples.Sequential
  dependencies:
    - base >=4.7 && <5
    - mtl
    - transformers
    - probability
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - QuickCheck
    - comonad
tests:
  test-open-games:
    main: THTests
    source-dirs: tests
    dependencies:
      - open-games-hs
      - template-haskell
      - base
      - probability
      - hspec
      - QuickCheck
