name: block-validation
version: '0.1.0.0'
synopsis: Protocol analysis 
category: Math
author: Philipp Zahn
maintainer: philipp.m.zahn@gmail.com
copyright: Philipp Zahn
license: MIT
extra-source-files:
- README.md


library:
  source-dirs: src
  exposed-modules:
    - BlockValidation.Representations.Internal
    - BlockValidation.HonestBehavior
    - BlockValidation.Representations.TypesFunctions

dependencies:
  - base >= 4.7 && < 5
  - template-haskell
  - generic-random
  - open-games-hs
  - probability
  - splitmix
  - mwc-random
  - mtl
  - transformers
  - poly
  - profunctors
  - parsec
  - comonad
  - extra
  - fgl
  - graphviz
  - lens
  - typed-process
  - criterion
  - random
  - algebraic-graphs
  - NumInstances
  - containers



executables:
  block-validation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - block-validation

tests:
  test-block-validation:
    main: Spec.hs
    source-dirs: src/test
    dependencies:
      - block-validation
      - template-haskell
      - base
      - hspec
      - QuickCheck

  eq-tests:
    buildable: True
    main: Equilibrium
    source-dirs: test
    dependencies:
      - block-validation
      - template-haskell
      - base
      - hspec
      - QuickCheck
      - generic-random

