name: open-games-hs
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges & other contributors
maintainer: juleshedges.invariant@gmail.com
copyright: 2020 Jules Hedges & other contributors
license: AGPL
github: jules-hedges/open-games-hs
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
    - Engine.OpenGamesClass
    - Engine.Diagnostics
    - Engine.PureOpenGames
    - Engine.BayesianOpenGames
    - Engine.BayesianDiagnostics
    - Engine.BayesianDiagnosticsTLL
    - Engine.StatefulPayoffs
    - Engine.OpticClass
    - Engine.SubgamePerfect
    - Engine.DecisionClass
    - Engine.StatefulBayesian
    - Engine.DependentDecision
    - Engine.PureNumerical
    - Engine.PureNumerical2
    - Engine.PureNumerical3
    - Engine.PolyNumerical
    - Preprocessor.THSyntax
    - Preprocessor.TH
    - Preprocessor.Compile
    - Preprocessor.AbstractSyntax
    - Preprocessor.Preprocessor
    - Preprocessor.Parser
    - Preprocessor.Lambda
    - Examples.Bimatrix
    - Examples.Sequential
    - Examples.Bayesian
    - Examples.Signalling
    - Examples.SimpleAuction
    - Examples.LemonMarket
    - Examples.ResaleMarket
    - Examples.KD.Bimatrix
    - Examples.KD.Sequential
    - Examples.KD.LemonMarket
    - Examples.EcologicalPublicGood.EcologicalPublicGood
    - Examples.Governance.Monitoring
    - Examples.Governance.ChoosingGames
    - Examples.Governance.ChoosingRandomly
    - Examples.Governance.ChoosingStatefulRandomly
    - Examples.Governance.ThirdOption
    - Examples.SubgameTest
    - Examples.Governance.Irrigation
    - Examples.Governance.IrrigationRandom
    - Examples.Governance.IrrigationRandom2
    - Examples.Governance.VotingGames
    - Examples.Governance.InstitutionProcess
    - Examples.PermitSale.PermitSale
    - Examples.RepetitionTest
    - Examples.Consensus.Simple
    - Examples.Consensus.Censor
    - Examples.Consensus.CensorStrategicAttacker
    - Examples.Consensus.AndGate
  dependencies:
    - base >=4.7 && <5
    - mtl
    - transformers
    - probability
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - QuickCheck
    - comonad
tests:
  test-open-games:
    main: THTests
    source-dirs: tests
    dependencies:
      - open-games-hs
      - template-haskell
      - base
      - probability
      - hspec
      - QuickCheck
