name: open-games-hs
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges, André Videla, Philipp Zahn & other contributors
maintainer: philipp.zahn@protonmail
copyright: Jules Hedges, André Videla, Philipp Zahn & other contributors
license: AGPL
extra-source-files:
- README.md


library:
  source-dirs: src
  exposed-modules:
    - Engine.AtomicGames
    - Engine.BayesianGames
    - Engine.Diagnostics
    - Engine.Engine
    - Engine.OpenGames
    - Engine.OpticClass
    - Engine.TLL
    - Preprocessor.AbstractSyntax
    - Preprocessor.Compile
    - Preprocessor.Lambda
    - Preprocessor.Parser
    - Preprocessor.THSyntax
    - Preprocessor.TH
    - Preprocessor.Types
    - Preprocessor.Preprocessor
    - Examples.SimultaneousMoves
    - Examples.Bayesian
    - Examples.Decision
    - Examples.SequentialMoves

dependencies:
    - base >=4.7 && <5
    - mtl
    - transformers
    - probability
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - QuickCheck
    - comonad
    - haskeline

executables:
  open-games-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-games-hs


